openapi: '3.1.1'
info:
  title: DemoTemplateServices.Api | v1
  version: 1.0.0
servers:
  - url: http://localhost:52152/
paths:
  '/api/v1/products/{productId}/move-card/operations':
    get:
      tags:
        - Карточка движения товара (КДТ) - операции
      summary: Получить операции карточки движения товара
      parameters:
        - name: productId
          in: path
          description: "Идентификатор товарной позиции (BookId)\r\n<br />Пример: 3136715 - Классика в комиксах: Пушкин. Капитанская дочка"
          required: true
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
          example: 3136715
        - name: partnerId
          in: query
          description: "Идентификатор магазина (код ОРС)\r\n<br />Пример: 469 - Братиславская 2"
          required: true
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
          example: 469
        - name: 'filters[documentIssuedFromAt]'
          in: query
          description: "Дата выпуска документа (основная дата проведения операции) - минимальный порог (включительно)\r\n<br />Если не указан - минимальный порог отсутствует"
          schema:
            type: string
            format: date-time
            example: '2026-05-01T12:00:00.000Z'
          example: '2026-05-01T12:00:00.000Z'
        - name: 'filters[documentIssuedToAt]'
          in: query
          description: "Дата выпуска документа (основная дата проведения операции) - максимальный порог (включительно)\r\n<br />Если не указан - максимальный порог отсутствует"
          schema:
            type: string
            format: date-time
            example: '2026-05-31T12:00:00.000Z'
          example: '2026-05-31T12:00:00.000Z'
        - name: sort
          in: query
          description: "Параметр сортировки\r\n<br />Если не указан, то будет использована сортировка по умолчанию (\"documentCreatedAtDesc\")<p>Варианты:</p><ul><li><i>documentIssuedAt</i> - Дата выпуска документа (основная дата проведения операции) (от старых к новым)</li><li><i>documentIssuedAtDesc</i> - Дата выпуска документа (основная дата проведения операции) (от новых к старым)</li></ul>"
          schema:
            $ref: '#/components/schemas/FetchProductOperationsSort'
        - name: 'page[number]'
          in: query
          description: "Номер запрашиваемой страницы\r\n<br />Если не указан - будет возвращена первая страница (номер 1)\r\n<br />\r\n[https://jsonapi.org/format/#fetching-pagination](https://jsonapi.org/format/#fetching-pagination)"
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
            example: 1
          example: 1
        - name: 'page[size]'
          in: query
          description: "Количество элементов на одной странице ответа\r\n<br />Если не указано - используется значение по умолчанию в зависимости от запрашиваемого метода\r\n<br />\r\n[https://jsonapi.org/format/#fetching-pagination](https://jsonapi.org/format/#fetching-pagination)"
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
            example: 100
          example: 100
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IApiSimpleCollectionResponseOfGetProductOperationsResponseData'
        '400':
          description: 'Не переданы обязательные параметры, либо параметры переданы, но в некорректном формате'
          content:
            application/json:
              schema: { }
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema: { }
        '404':
          description: Сервис недоступен
          content:
            application/json:
              schema: { }
        '423':
          description: Интеграция с РМ выключена в настройках программы на стороне 1С:УТ
          content:
            application/json:
              schema: { }
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema: { }
components:
  schemas:
    ApiResource:
      required:
        - type
        - id
      type: object
      properties:
        type:
          type: string
          description: "Тип ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-identifier-objects](https://jsonapi.org/format/#document-resource-identifier-objects)"
        id:
          type: string
          description: "Идентификатор ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-identifier-objects](https://jsonapi.org/format/#document-resource-identifier-objects)"
      additionalProperties: false
    ApiResponsePagination:
      required:
        - size
        - number
        - total
        - count
        - totalPages
      type: object
      properties:
        size:
          type: integer
          description: Количество результатов на одну страницу
          format: int32
          example: 100
        number:
          type: integer
          description: Номер Текущей страницы результатов
          format: int32
          example: 1
        total:
          type: integer
          description: Всего найдено результатов поиска
          format: int32
          example: 1
        count:
          type: integer
          description: Количество результатов на текущей странице
          format: int32
          example: 1
        totalPages:
          type: integer
          description: Всего страниц результатов
          format: int32
          example: 1
      additionalProperties: false
    ApiSimpleCollectionResourceOfGetProductOperationsResponseData:
      allOf:
        - $ref: '#/components/schemas/ApiSimpleResourceOfGetProductOperationsResponseData'
        - { }
      additionalProperties: false
      description: Данные ответа
    ApiSimpleResourceOfGetProductOperationsResponseData:
      allOf:
        - $ref: '#/components/schemas/ApiResource'
        - required:
            - attributes
          type: object
          properties:
            attributes:
              $ref: '#/components/schemas/GetProductOperationsResponseData'
    FetchProductOperationsSort:
      enum:
        - documentIssuedAt
        - documentIssuedAtDesc
        - 
    GetProductOperationsResponseData:
      required:
        - productId
        - partnerId
        - quantityInTransit
        - operations
      type: object
      properties:
        productId:
          type: integer
          description: "Идентификатор товарной позиции (ProductId)\r\n<br />Пример: 3136715 - Классика в комиксах: Пушкин. Капитанская дочка"
          format: int32
          example: 3136715
        partnerId:
          type: integer
          description: "Идентификатор магазина (код ОРС)\r\n<br />Пример: 469 - Братиславская 2"
          format: int32
          example: 469
        quantityInTransit:
          type: integer
          description: Количество экземпляров этого товара на пути в указанный магазин на текущий момент (момент выполнения запроса)
          format: int32
          example: 1
        operations:
          type: array
          items:
            $ref: '#/components/schemas/ProductMoveCardOperation'
          description: Операции движения по товару
      additionalProperties: false
      description: "Атрибуты ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-object-attributes](https://jsonapi.org/format/#document-resource-object-attributes)"
    IApiCollectionResponseMeta:
      required:
        - pagination
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/ApiResponsePagination'
      additionalProperties: false
      description: Мета-информация ответа на запрос к API
    IApiSimpleCollectionResponseOfGetProductOperationsResponseData:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ApiSimpleCollectionResourceOfGetProductOperationsResponseData'
        meta:
          $ref: '#/components/schemas/IApiCollectionResponseMeta'
      additionalProperties: false
    ProductMoveCardOperation:
      required:
        - documentId
        - documentTypeId
        - documentTypeName
        - documentIssuedAt
        - quantity
        - totalQuantityInShopAfterOperation
        - productInOperationPrice
      type: object
      properties:
        documentId:
          type: string
          description: Идентификатор документа в системе 1С:УТ
          example: 123456
        documentTypeId:
          type: string
          description: Идентификатор типа документа
          example: 3
        documentTypeName:
          type: string
          description: Название типа документа
          example: Сокращение
        documentIssuedAt:
          type: string
          description: Дата выпуска документа (основная дата проведения операции)
          format: date-time
          example: '2026-05-15T12:00:00.000Z'
        quantity:
          type: integer
          description: 'Количество товара по документу (приход «+», расход «-»)'
          format: int32
          example: -3
        totalQuantityInShopAfterOperation:
          type: integer
          description: Количество товара на остатках магазина после выполнения операции
          format: int32
          example: 27
        productInOperationPrice:
          type: number
          description: Цена товара для конкретно этой операции
          format: double
          example: 1533.0000
      additionalProperties: false
tags:
  - name: Карточка движения товара (КДТ) - операции
