openapi: '3.1.1'
info:
  title: DemoTemplateServices.Api | v1
  version: 1.0.0
servers:
  - url: http://localhost:52152/
paths:
  '/api/v1/products/{productId}/move-card/operations':
    get:
      tags:
        - Карточка движения товара (КДТ) - операции
      summary: Получить операции карточки движения товара
      parameters:
        - name: productId
          in: path
          description: "Идентификатор товарной позиции (BookId)\r\n<br />Пример: 3136715 - Классика в комиксах: Пушкин. Капитанская дочка"
          required: true
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
          example: 3136715
        - name: partnerId
          in: query
          description: "Идентификатор магазина (код ОРС)\r\n<br />Пример: 469 - Братиславская 2"
          required: true
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
          example: 469
        - name: 'filters[documentCalculatedFromAt]'
          in: query
          description: "Дата расчёта документа (основная дата проведения операции) - минимальный порог (включительно)\r\n<br />Если не указан - минимальный порог отсутствует"
          schema:
            type: string
            format: date-time
            example: '2026-05-01T12:00:00.000Z'
          example: '2026-05-01T12:00:00.000Z'
        - name: 'filters[documentCalculatedToAt]'
          in: query
          description: "Дата расчёта документа (основная дата проведения операции) - максимальный порог (включительно)\r\n<br />Если не указан - максимальный порог отсутствует"
          schema:
            type: string
            format: date-time
            example: '2026-05-31T12:00:00.000Z'
          example: '2026-05-31T12:00:00.000Z'
        - name: sort
          in: query
          description: "Параметр сортировки\r\n<br />Если не указан, то будет использована сортировка по умолчанию (\"documentCreatedAtDesc\")<p>Варианты:</p><ul><li><i>documentCalculatedAt</i> - Дата расчёта документа (основная дата проведения операции) (от старых к новым)</li><li><i>documentCalculatedAtDesc</i> - Дата расчёта документа (основная дата проведения операции) (от новых к старым)</li></ul>"
          schema:
            $ref: '#/components/schemas/FetchProductOperationsSort'
        - name: 'page[number]'
          in: query
          description: "Номер запрашиваемой страницы\r\n<br />Если не указан - будет возвращена первая страница (номер 1)\r\n<br />\r\n[https://jsonapi.org/format/#fetching-pagination](https://jsonapi.org/format/#fetching-pagination)"
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
            example: 1
          example: 1
        - name: 'page[size]'
          in: query
          description: "Количество элементов на одной странице ответа\r\n<br />Если не указано - используется значение по умолчанию в зависимости от запрашиваемого метода\r\n<br />\r\n[https://jsonapi.org/format/#fetching-pagination](https://jsonapi.org/format/#fetching-pagination)"
          schema:
            maximum: 2147483647
            minimum: 1
            type: integer
            format: int32
            example: 100
          example: 100
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IApiErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IApiErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IApiErrorResponse'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IApiSimpleCollectionResponseOfGetProductOperationsResponseData'
components:
  schemas:
    ApiResource:
      required:
        - type
        - id
      type: object
      properties:
        type:
          type: string
          description: "Тип ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-identifier-objects](https://jsonapi.org/format/#document-resource-identifier-objects)"
        id:
          type: string
          description: "Идентификатор ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-identifier-objects](https://jsonapi.org/format/#document-resource-identifier-objects)"
      additionalProperties: false
    ApiResponseError:
      required:
        - code
        - title
        - id
        - status
      type: object
      properties:
        id:
          type: string
          description: "Уникальный идентификатор для данного конкретного случая возникновения проблемы\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
          format: uuid
        status:
          type: string
          description: "Код состояния HTTP, относящийся к данной проблеме.\r\n<br />\n            Выражается в виде строкового значения.\r\n<br />\n            Этот код ДОЛЖЕН быть предоставлен.\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        code:
          type: string
          description: "Код ошибки, специфичный для приложения.\r\n<br />\n            Выражается в виде строкового значения.\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        title:
          type: string
          description: "Краткое, понятное человеку описание проблемы.\r\n<br />\n            НЕ ДОЛЖНО меняться от случая к случаю для неё\r\n<br />\n            (за исключением случаев локализации)\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        detail:
          type:
            - 'null'
            - string
          description: "Понятное человеку описание проблемы, специфичное для данного случая.\r\n<br />\n            Как и\r\nTitle, может быть локализовано.\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        source:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/ApiResponseErrorSource'
      additionalProperties: false
    ApiResponseErrorSource:
      type: object
      properties:
        pointer:
          type:
            - 'null'
            - string
          description: "Указатель JSON [\r\n[RFC6901](https://datatracker.ietf.org/doc/html/rfc6901)] на значение в документе запроса, вызвавшее ошибку.\r\n<br />\n            [например, \"/data\" для основного объекта данных или \"/data/attributes/title\" для конкретного атрибута]\r\n<br />\n            Этот указатель ДОЛЖЕН указывать на существующее значение в документе запроса;\r\n<br />\n            Если его нет, клиент ДОЛЖЕН просто игнорировать указатель.\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        parameter:
          type:
            - 'null'
            - string
          description: "Строка, указывающая, какой параметр запроса URI вызвал ошибку\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
        header:
          type:
            - 'null'
            - string
          description: "Строка, указывающая имя заголовка запроса, вызвавшего ошибку\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
      additionalProperties: false
      description: "Источник ошибки API\r\n<br />\n            Объект, содержащий ссылки на основной источник ошибки.\r\n<br />\n            Он ДОЛЖЕН включать один из следующих членов или быть опущен\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
    ApiResponsePagination:
      required:
        - size
        - number
        - total
        - count
        - totalPages
      type: object
      properties:
        size:
          type: integer
          description: Количество результатов на одну страницу
          format: int32
          example: 100
        number:
          type: integer
          description: Номер Текущей страницы результатов
          format: int32
          example: 1
        total:
          type: integer
          description: Всего найдено результатов поиска
          format: int32
          example: 1
        count:
          type: integer
          description: Количество результатов на текущей странице
          format: int32
          example: 1
        totalPages:
          type: integer
          description: Всего страниц результатов
          format: int32
          example: 1
      additionalProperties: false
    ApiSimpleCollectionResourceOfGetProductOperationsResponseData:
      allOf:
        - $ref: '#/components/schemas/ApiSimpleResourceOfGetProductOperationsResponseData'
        - { }
      additionalProperties: false
      description: Данные ответа
    ApiSimpleResourceOfGetProductOperationsResponseData:
      allOf:
        - $ref: '#/components/schemas/ApiResource'
        - required:
            - attributes
          type: object
          properties:
            attributes:
              $ref: '#/components/schemas/GetProductOperationsResponseData'
    FetchProductOperationsSort:
      enum:
        - documentCalculatedAt
        - documentCalculatedAtDesc
      description: <p>Варианты:</p><ul><li><i>documentCalculatedAt</i> - Дата расчёта документа (основная дата проведения операции) (от старых к новым)</li><li><i>documentCalculatedAtDesc</i> - Дата расчёта документа (основная дата проведения операции) (от новых к старым)</li></ul>
    GetProductOperationsResponseData:
      required:
        - productId
        - partnerId
        - quantityInTransit
        - operations
      type: object
      properties:
        productId:
          type: integer
          description: "Идентификатор товарной позиции (ProductId)\r\n<br />Пример: 3136715 - Классика в комиксах: Пушкин. Капитанская дочка"
          format: int32
          example: 3136715
        partnerId:
          type: integer
          description: "Идентификатор магазина (код ОРС)\r\n<br />Пример: 469 - Братиславская 2"
          format: int32
          example: 469
        quantityInTransit:
          type: integer
          description: Количество экземпляров этого товара на пути в указанный магазин на момент этой операции
          format: int32
          example: 1
        operations:
          type: array
          items:
            $ref: '#/components/schemas/ProductMoveCardOperation'
          description: Операции движения по товару
      additionalProperties: false
      description: "Атрибуты ресурса\r\n<br />\r\n[https://jsonapi.org/format/#document-resource-object-attributes](https://jsonapi.org/format/#document-resource-object-attributes)"
    IApiCollectionResponseMeta:
      required:
        - pagination
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/ApiResponsePagination'
      additionalProperties: false
      description: Мета-информация ответа на запрос к API
    IApiErrorResponse:
      type: object
      properties:
        errors:
          type:
            - 'null'
            - array
          items:
            $ref: '#/components/schemas/ApiResponseError'
          description: "Ошибки, возникшие в результате  обработки запроса\r\n<br />\r\n[https://jsonapi.org/format/#error-objects](https://jsonapi.org/format/#error-objects)"
      additionalProperties: false
    IApiSimpleCollectionResponseOfGetProductOperationsResponseData:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ApiSimpleCollectionResourceOfGetProductOperationsResponseData'
        meta:
          $ref: '#/components/schemas/IApiCollectionResponseMeta'
      additionalProperties: false
    ProductMoveCardOperation:
      required:
        - documentId
        - documentTypeId
        - documentTypeName
        - documentCalculatedAt
        - quantity
        - totalQuantityInShopAfterOperation
        - productInOperationPrice
      type: object
      properties:
        documentId:
          type: string
          description: Идентификатор документа в системе 1С:УТ
          example: 123456
        documentTypeId:
          type: string
          description: Идентификатор типа документа
          example: 3
        documentTypeName:
          type: string
          description: Название типа документа
          example: Сокращение
        documentCalculatedAt:
          type: string
          description: Дата расчёта документа (основная дата проведения операции)
          format: date-time
          example: '2026-05-15T12:00:00.000Z'
        quantity:
          type: integer
          description: 'Количество товара по документу (приход «+», расход «-»)'
          format: int32
          example: -3
        totalQuantityInShopAfterOperation:
          type: integer
          description: Количество товара на остатках магазина после выполнения операции
          format: int32
          example: 27
        productInOperationPrice:
          type: number
          description: Цена товара для конкретно этой операции
          format: double
          example: 1533.0000
      additionalProperties: false
tags:
  - name: Карточка движения товара (КДТ) - операции
